### ISSUE TITLE
2022년 6월 16일 사전과제 1주차 모임

### ISSUE THREAD

**Issue by sigridjineth** [Web3-Study-with-Sigrid-Jin/ZKU-Summer-Cohort#1]
# 사전과제 1주차 모임
* 일시: 2022년 6월 16일 (목) 21시 - 21시 30분 온라인 구글 밋
* 구글 밋 링크: https://meet.google.com/tiv-mkss-zxt
## 이야기할 사항
* [x] 이 저장소를 어떻게 사용하는지 설명드릴 예정입니다.
* [x] 각자 얼마나 사전과제를 진행하셨나요? 혹시 제출하신 분이 계실까요?
 * 마감은 **June 27, 2022, 23:59 UTC** 입니다.
 * 합격자 발표는 **July 1, 2022, 23:59 UTC** 입니다.
* [x] 사전과제를 진행하면서 어떤 어려운 점이 있었나요? 반대로, 무엇을 얻을 수 있었나요?
* [x] 7월 4일부터 8월 31일까지 매주 오프라인 만남을 가질 예정입니다. 각자 어느 요일 및 시간대가 편하신가요?
 * 매주마다 서로 만나서 함께 과제를 해결해볼 예정입니다. ZK-SEL의 박지훈님, 그리고 저의 도움을 받아 현장 질의응답 및 토론을 진행합니다.
## Boom Labs
* 기초 개발 세션에 관심이 많았던 분도 계시고, 저희 DAO의 스터디 세션을 홍보하는 차원에서 1기 모집 일정을 알려드립니다.
* 구체적인 사항은 추후 공지 예정입니다.
- 기초 트랙: 폴리곤/이더리움 OR Dune Analytics 데이터 분석
- 심화 트랙: 니어/솔라나 OR ZKU 스터디 (이 모임; 별도로 운영 중) 
    - 6월 20일(월): 모집 시작
    - 6월 29일(수): 24:00PM 모집 마감
    - 7월 4일(월): 온보딩 참가자 확정 (이메일로)
    - 7월 9일(토): 프로그램 소개 자리 (저녁, 오프라인, 6PM~8PM)
    - 7월 11일(월): 트랙 시작  (8주)
        - 8월 31일~9월 2일 종료
## Harmony AMA
* 오늘 모임이 종료된 후, Harmony 트위터에서 AMA 세션을 진행할 예정이라고 하니 관심이 있으신 분은 참석해보시면 좋을 것 같습니다.
  * https://twitter.com/harmonyzkdao/status/1535483802822266882?s=20&t=WXX1xASEZDTyKlLYjYCg8g

-----
## 모임 사항 요약
* 우리의 목표는, 짧은 시간 동안에 하기 어려운 복잡한 논문 이해하기 보다는, ZK를 활용해 해커톤에 나가서 각자 자신만의 토이 프로젝트를 할 수 있는 레벨로 끌어 올리는 것으로 잡자고 이야기를 나눴습니다.
* 각자 이번 주까지 진행한 사항을 여기 댓글로 링크에 달아주세요 :)
   * 링크: https://github.com/Web3-Study-with-Sigrid-Jin/ZKU-Summer-Cohort/issues/1
* 6월 23일(목) 22시 - 22시 30분 사전과제 진행사항 체크하는 온라인 모임이 있습니다.
   * 구글 밋 링크: https://meet.google.com/gii-tfeg-etn
* 깃헙 저장소 초대를 드렸습니다. 이메일을 확인해주세요!
   * 앞으로 깃헙 저장소에서 회의록 작성, 자료 취합 등을 정리할 예정이에요.
   * 깃헙 아이디를 아직 알려주지 않으셨거나, 초대를 아직 받지 못하신 분은 카톡방에 깃헙 아이디를 알려주세요.

**Comment by jian7061** [comment]
1. 각자 얼마나 사전과제를 진행하셨나요? 혹시 제출하신 분이 계실까요?
 => 2주전쯤 제출했으나 solidity 과제에 확신이 없어서 오늘 다시 업데이트하였습니다.

2. 사전과제를 진행하면서 어떤 어려운 점이 있었나요? 반대로, 무엇을 얻을 수 있었나요?
 => seller가 completePurchase 콜해야하는데 조건(modifier)에는 caller가 buyer라는게 왜 들어가는지...? 이해가 안되네요.
    그리고 나뭇잎 개수 세는 문제는 제출은 했으나 완전 헛다리 짚고 있을 수도 있다는 생각도 들고.. 다른 분들 의견이 궁금합니다..!
    
    얻게 된 것은, 당연히 알고 있다고 생각한 개념들을 말로 풀어서 적어보니 정확히 알지 못한 개념들도 있어서 다시 한 번 찾아보고 정확하게 숙지하 
    게 되었습니다.

3. 7월 4일부터 8월 31일까지 매주 오프라인 만남을 가질 예정입니다. 각자 어느 요일 및 시간대가 편하신가요?
 => 주중은 전부 가능합니다.

**Comment by mrclo90** [comment]
1. 각자 얼마나 사전과제를 진행하셨나요? 혹시 제출하신 분이 계실까요?
    => 현재 솔리디티 코드 작성 과제 이전까지 완료하였습니다.
2. 사전과제를 진행하면서 어떤 어려운 점이 있었나요? 반대로, 무엇을 얻을 수 있었나요?
    => 코드를 직접 짜는 데 익숙하지 않다보니 조금 애를 먹고 있습니다 ㅠㅡㅠ 반대로 영지식 증명을 적용헤서 계속 문제를 해결하려고 하는 게 좋았던 점 같습니다. 
3. 7월 4일부터 8월 31일까지 매주 오프라인 만남을 가질 예정입니다. 각자 어느 요일 및 시간대가 편하신가요?
   => 주중에는 7시 이후, 일요일 오전, 토요일은 하루 종일 가능합니다:)

**Comment by 0xjunha** [comment]
1. 각자 얼마나 사전과제를 진행하셨나요? 혹시 제출하신 분이 계실까요?
  => 약 1주일 전 제출했습니다.
2. 사전과제를 진행하면서 어떤 어려운 점이 있었나요? 반대로, 무엇을 얻을 수 있었나요?
  => 나뭇잎 문제 풀이를 적어 내긴 했는데, 몹시 비효율적인 방법 같아서 더 고민해봐야할 것 같습니다. 솔리디티 코드 작성해보면서 컨트랙트 본연의 기능에 충실한 예제 같아서 디앱 로직의 기본에 대해 이해할 수 있었습니다.
3. 7월 4일부터 8월 31일까지 매주 오프라인 만남을 가질 예정입니다. 각자 어느 요일 및 시간대가 편하신가요?
  => 주중은 7~8시 이후가 가능하고, 주말은 하루종일 가능합니다.
