### ISSUE TITLE
2022년 6월 9일 오리엔테이션

### ISSUE THREAD

**Issue by sigridjineth** [Web3-Study-with-Sigrid-Jin/ZKU-Summer-Cohort#3]
## 오리엔테이션 요약
- 다음 링크의 사전 과제를 6월 27일까지 제출해야 합니다.
- 6월 16일, 23일 목요일 오후 10시에 각각 본인의 진행상황 공유 시간 및 질의응답을 받겠습니다. (본인이 다 제출했더라도, 아직 과제를 진행하고 있는 동료를 위해 꼭 참석해주세요)
- 사전 과제 링크: https://zku.one/apply-now

- (참가 의향이 있으신 분은) 본인의 깃헙 및 노션 아이디를 알려주세요.

## Disclaimer
1. 만약 개발 실력이 우려되어 참석이 어려우신 분이라면, 7월에 있을 Boom Labs의 개발 기초 세션에 정중히 초대드리도록 하겠습니다.
2. 저는 zku와 공식적인 관계가 없으며, 대신 zku graduate(수료생)의 자격으로 순수히 ZK에 대해 더 많이 논의하는 개발자가 많아졌으면 좋겠다고 하는 선의의 차원에서 이 프로젝트를 진행하고 있습니다. 따라서 해당 ZKDAO가 약속하는 금전적, 비금전적 대가와는 어떠한 직간접적인 관련도 없음을 미리 밝힙니다.

**Comment by realsigridjin** [comment]
오리엔테이션 자료 링크: https://drive.google.com/file/d/1s5xEZ56SmGIFy4TmEsAO1NqmF5Ff1BPe/view?usp=sharing
