### ISSUE TITLE
2022년 6월 23일 사전과제 2주차 모임

### ISSUE THREAD

**Issue by sigridjineth** [Web3-Study-with-Sigrid-Jin/ZKU-Summer-Cohort#4]
# 사전과제 2주차 모임
* 일시: 2022년 6월 23일 (목) 22시 - 22시 15분 온라인 구글 밋
* 구글 밋 링크: https://meet.google.com/gii-tfeg-etn
## 이야기할 사항
* [x] 각자 얼마나 사전과제를 진행하셨나요? 혹시 제출하신 분이 계실까요?
 * 마감은 **June 27, 2022, 23:59 UTC** 입니다.
 * 합격자 발표는 **July 1, 2022, 23:59 UTC** 입니다.
 * 7/2(KST)에 합격자 발표가 나오시면 저에게 개인적으로 카톡 알려주시기 바랍니다. (해당 인원 대상으로 다시 단톡방을 만들도록 하겠습니다.)
* [ ] 사전과제를 진행하면서 어떤 어려운 점이 있었나요? 반대로, 무엇을 얻을 수 있었나요?
* [ ] 7월 4일부터 8월 31일까지 매주 오프라인 만남을 가질 예정입니다. 각자 어느 요일 및 시간대가 편하신가요?
 * 매주마다 서로 만나서 함께 과제를 해결해볼 예정입니다. ZK-SEL의 박지훈님, 그리고 저의 도움을 받아 현장 질의응답 및 토론을 진행합니다.
 * 주중 1회 19시 ~ 21시 언주역 근처를 생각하고 있습니다. (월요일 / 수요일 / 목요일 중 하루)
* [ ] 깃헙 아이디를 아직 알려주지 않으셨거나, 초대를 아직 받지 못하신 분은 카톡방에 깃헙 아이디를 알려주세요.

## Boom Labs
* 원래는 7월부터 교육 트랙이 진행될 예정이었으나, 7월에는 매주 핸즈온 밋업을 진행하면서 인지도를 높인 다음에 8월부터 참가자를 모집하기로 했습니다.
* 구체적인 사항은 추후 공지 예정입니다.
- 기초 트랙: 폴리곤/이더리움 OR Dune Analytics 데이터 분석
- 심화 트랙: 니어/솔라나 OR ZKU 스터디 (이 모임; 별도로 운영 중)

**Comment by jian7061** [comment]
지원 어제 마감되었어요!

**Comment by realsigridjin** [comment]
## 이번주 목요일 모임 요약
### 일정
* 6월 27일(월) 부터 매주 19시-21시 진행합니다.
* 장소는 강남역 논스 제네시스를 생각 중이며, 추후 다시 공지하겠습니다.
### 모임 전까지 해올 것
* 다음 링크의 Preface와 Section 1 읽어오기
* https://ethspring.com/docs/zero-knowledge/0-preface
* Section 1의 Quest 해보고, Pull Request 보내기
 * Play with this [Interactive ZK 3-coloring demo](http://web.mit.edu/~ezyang/Public/graph/svg.html) (after reading the "illustrated primer" reading). Try to answer Exercises 1 and 2 at the bottom of the page.
